# Generated by Django 3.2.6 on 2022-04-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomDetails',
            fields=[
                ('classroom_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('date_of_creation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classroomDetails',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('userName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=1000)),
                ('salt', models.CharField(default='', max_length=1000)),
                ('position_teacher', models.CharField(default='False', max_length=1000)),
                ('position_student', models.CharField(default='False', max_length=1000)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='QuizDetails',
            fields=[
                ('quiz_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=1000)),
                ('totalMarks', models.CharField(max_length=10000)),
                ('classroom_code', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.classroomdetails')),
            ],
            options={
                'db_table': 'quizDetails',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('student_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='Attendence.login')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=100)),
                ('student_mobileNumber', models.CharField(max_length=1000)),
                ('student_image', models.CharField(max_length=100000, null=True)),
            ],
            options={
                'db_table': 'studentDetails',
            },
        ),
        migrations.CreateModel(
            name='TeachersDetails',
            fields=[
                ('teachers_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='Attendence.login')),
                ('teachers_name', models.CharField(max_length=100)),
                ('teachers_email', models.CharField(max_length=100)),
                ('teachers_mobileNumber', models.CharField(max_length=1000)),
                ('teachers_image', models.CharField(blank=True, max_length=20000, null=True)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.CharField(max_length=10000)),
                ('obtained_marks', models.CharField(max_length=10000)),
                ('classroom_code', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.classroomdetails')),
                ('quiz_id', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.quizdetails')),
                ('student_userName', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.studentdetails')),
                ('teachers_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.teachersdetails')),
            ],
            options={
                'db_table': 'quizResult',
            },
        ),
        migrations.AddField(
            model_name='quizdetails',
            name='teachers_userName',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.teachersdetails'),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer_option1', models.CharField(max_length=1000)),
                ('answer_option2', models.CharField(max_length=1000)),
                ('answer_option3', models.CharField(max_length=1000)),
                ('answer_option4', models.CharField(max_length=1000)),
                ('correct_answer_option', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('classroom_code', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.classroomdetails')),
                ('quiz_id', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.quizdetails')),
                ('teachers_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.teachersdetails')),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=10000)),
                ('classroom_code', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.classroomdetails')),
                ('teachers_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.teachersdetails')),
            ],
            options={
                'db_table': 'notes',
            },
        ),
        migrations.AddField(
            model_name='classroomdetails',
            name='teacher_userName',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.teachersdetails'),
        ),
        migrations.CreateModel(
            name='ClassAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_code', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.classroomdetails')),
                ('student_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.studentdetails')),
            ],
            options={
                'db_table': 'classAccess',
            },
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=1000)),
                ('present', models.CharField(max_length=10000000)),
                ('classroom_code', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.classroomdetails')),
                ('teachers_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.teachersdetails')),
            ],
            options={
                'db_table': 'attendence',
            },
        ),
    ]
