# Generated by Django 3.2.6 on 2022-04-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
    ]
