# Generated by Django 3.2.6 on 2022-04-14 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0002_alter_questions_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='student_gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
