# Generated by Django 3.2.6 on 2022-04-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0004_classaccess_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='present',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.studentdetails'),
        ),
    ]
