# Generated by Django 4.0.4 on 2022-05-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0005_alter_attendence_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='student_userName',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Attendence.studentdetails'),
        ),
    ]
