# Generated by Django 4.0.4 on 2022-05-04 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0006_alter_quizresult_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomdetails',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
