# Generated by Django 4.0.4 on 2022-05-04 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0007_classroomdetails_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='marks',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
