# Generated by Django 4.0.4 on 2022-05-04 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0008_questions_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdetails',
            name='quiz_topic',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
