# Generated by Django 4.0.4 on 2022-05-07 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0009_quizdetails_quiz_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='file',
            new_name='decpriction_of_notes',
        ),
        migrations.AddField(
            model_name='notes',
            name='notes',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='title_of_notes',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
