# Generated by Django 4.0.4 on 2022-05-16 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0010_rename_file_notes_decpriction_of_notes_notes_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
