# Generated by Django 4.0.4 on 2022-05-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0013_quizaccess_remove_attendence_present_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='students_userNames',
        ),
    ]
